---
- hosts: all
  any_errors_fatal: true # stop if anything is wrong
  become: false # do as myself, not root
  serial: 1

  tasks:
  
  - name: change password for root user on System {{ inventory_hostname }}
    become: true # sudo
    vars:
      new_password: "{{ lookup('onepassword',  ''+inventory_hostname+'', vault='LinuxRootPasswords') }}"
    user:
      name: root
      update_password: always
      password: "{{ new_password | password_hash('sha512') }}"

